name: DMHelper CI Windows Workflow

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    defaults:
      run:
        shell: pwsh

    steps:
      # -------------------------
      # Checkout repository
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # Install Qt (MSVC 2022)
      # -------------------------
      - name: Install Qt 6.10.1 (MSVC 2022)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.1
          arch: win64_msvc2022_64
          tools: 'tools_vcredist,qt.tools.vcredist_64 tools_vcredist,qt.tools.vcredist_msvc2022_x64 tools_ifw'
          cache: true
          modules: 'qtmultimedia qtnetworkauth qtimageformats'
          add-tools-to-path: 'true'
          archives: 'qttranslations qttools qtsvg qtbase opengl32sw d3dcompiler_47'

      # -------------------------
      # Ensure 7-Zip exists
      # (Windows runner already has it, but we assert it)
      # -------------------------
      - name: Verify 7-Zip
        run: |
          Test-Path "C:\Program Files\7-Zip\7z.exe"
          if (-not (Test-Path "C:\Program Files\7-Zip\7z.exe")) {
            throw "7-Zip not found"
          }

      # -------------------------
      # Check the full file tree
      # -------------------------
      - name: Debug Workspace output pre-build
        working-directory: ${{ runner.workspace }}
        run: |
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo 'github.workspace === ${{ github.workspace }}'
          echo ${{env.QT_ROOT_DIR}}
          Get-ChildItem -Recurse -File

      # -------------------------
      # Run build & deploy script
      # -------------------------
      - name: Build DMHelper (MSVC Release)
        working-directory: ${{ github.workspace }}/DMHelper
        run: |
          Get-ChildItem -Recurse -File -Filter "buildanddeploy_msvc64_cmake.ps1"
          "y" | pwsh -NoProfile -ExecutionPolicy Bypass -File buildanddeploy_msvc64_cmake.ps1
      
      # -------------------------
      # Check the full file tree
      # -------------------------
      - name: Debug Workspace output post-build
        working-directory: ${{ runner.workspace }}
        run: |
          Get-ChildItem -Recurse -File

      # -------------------------
      # Upload artifacts
      # -------------------------
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: DMHelper-Windows-Installer
          path: |
            DMHelper-64-bit-release-Installer.exe

      - name: Upload ZIP Distribution
        uses: actions/upload-artifact@v4
        with:
          name: DMHelper-Windows-Zip
          path: |
            DMHelper-64-bit-release.zip
